#!/usr/bin/env python3

digits = {
0: """
 ###
#   #
#   #
#   #
#   #
 ###
""",
1: """
  #
 ##
# #
  #
  #
#####
""",
2: """
 ###
#   #
   #
  #
 #
#####
""",
3: """
 ###
#   #
  ##
    #
#   #
 ###
""",
4: """
#   #
#   #
#####
    #
    #
    #
""",
5: """
#####
#
#####
    #
    #
#####
""",
6: """
#####
#
#
#####
#   #
#####
""",
7: """
#####
    #
   #
  #
 #
#
""",
8: """
 ###
#   #
 ###
#   #
#   #
 ###
""",
9: """
#####
#   #
#####
    #
    #
    #
"""
}

from datetime import datetime

def print_digit_lines(nums, line_num):
    for digit in nums:
        line = digits[int(digit)].split('\n')[line_num]
        print(line.ljust(8), end='')


def main():
    now = datetime.now()
    hour = str(now.hour).zfill(2)
    minute = str(now.minute).zfill(2)

    for i in range(7):
        print_digit_lines(hour, i)

        if i == 2 or i == 5:
            print('#  ', end='')
        else:
            print('   ', end='')

        print_digit_lines(minute, i)
        print()

if __name__ == '__main__':
    main()
